members:
  huangw: ['黄巍', 'huangw@pe-po.com']
  xuyc: ['徐以臣', 'xuyc@pe-po.com']
  sunyr: ['孙云蕊', 'sunyr@pe-po.com']
  lizh: ['李中华', 'lizh@pe-po.com']
  songcy: ['宋春月', 'songcy@pe-po.com']  
  du: ['杜丽玲', 'du@pe-po.com']
  zhaogl: ['赵桂兰', 'zhaogl@pe-po.com']
  wangh: ['王浩', 'wangh@pe-po.com']
  liudx: ['刘东旭', 'liudx@pe-po.com']
  zhangy: ['张祎', 'zhangy@pe-po.com']
  wangqh: ['王清华', 'wangqh@pe-po.com']
  cuibg: ['崔保国', 'cuibg@pe-po.com']
  lixf: ['李现凤', 'lixf@pe-po.com']
  zhaoxx: ['赵秀秀', 'zhaoxx@pe-po.com']

